# Generated by Django 3.2 on 2022-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('B', 'Breakfast'), ('D', 'Drink'), ('DI', 'Dinner'), ('L', 'Lunch')], default='D', max_length=10),
        ),
    ]
