# Generated by Django 3.2 on 2022-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('drinks', 'Drink'), ('dinner', 'Dinner'), ('lunch', 'Lunch')], default='drinks', max_length=10),
        ),
    ]
