# Generated by Django 3.2 on 2022-05-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_staff_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Stuff',
        ),
    ]
